# Generated by Django 3.2.9 on 2021-11-12 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(blank=True, max_length=100)),
                ('price_items', models.DecimalField(blank=True, decimal_places=4, max_digits=6)),
                ('fecha_items', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DinnerPlates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_dinner', models.CharField(blank=True, max_length=40)),
                ('tamanio', models.CharField(blank=True, max_length=10)),
                ('price_dinner', models.DecimalField(blank=True, decimal_places=4, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='ExtraSubs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_extras', models.CharField(blank=True, max_length=25)),
                ('price_extra_sub', models.DecimalField(blank=True, decimal_places=4, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_pasta', models.CharField(blank=True, max_length=40)),
                ('price_pasta', models.DecimalField(blank=True, decimal_places=4, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Salads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_salads', models.CharField(blank=True, max_length=40)),
                ('price_salads', models.DecimalField(blank=True, decimal_places=4, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_thing', models.CharField(blank=True, max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Toppings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tooping', models.CharField(blank=True, max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_subs', models.CharField(blank=True, max_length=40)),
                ('tamanio', models.CharField(blank=True, max_length=10)),
                ('price_subs', models.DecimalField(blank=True, decimal_places=4, max_digits=5)),
                ('extra_sub', models.ManyToManyField(to='orders.ExtraSubs')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialSicilianPizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_special_sic', models.CharField(default='Special Sicilian Pizza', max_length=40)),
                ('tamanio', models.CharField(blank=True, max_length=10)),
                ('price_special_sic', models.DecimalField(blank=True, decimal_places=4, max_digits=5)),
                ('toppings', models.ManyToManyField(to='orders.Toppings')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialRegularPizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_special_reg', models.CharField(default='Special Regular Pizza', max_length=40)),
                ('tamanio', models.CharField(blank=True, max_length=10)),
                ('price_special_reg', models.DecimalField(blank=True, decimal_places=4, max_digits=5)),
                ('toppings', models.ManyToManyField(to='orders.Toppings')),
            ],
        ),
        migrations.CreateModel(
            name='SicilianPizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_sic_pizza', models.CharField(blank=True, max_length=30)),
                ('tamanio', models.CharField(blank=True, max_length=10)),
                ('price_sic_pizza', models.DecimalField(blank=True, decimal_places=4, max_digits=5)),
                ('quantity_top', models.IntegerField(blank=True, max_length=1, unique=True)),
                ('toppings', models.ManyToManyField(to='orders.Toppings')),
            ],
        ),
        migrations.CreateModel(
            name='RegularPizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_reg_pizza', models.CharField(blank=True, max_length=30)),
                ('tamanio', models.CharField(blank=True, max_length=10)),
                ('price_reg_pizza', models.DecimalField(blank=True, decimal_places=4, max_digits=5)),
                ('quantity_top', models.IntegerField(blank=True, max_length=1, unique=True)),
                ('toppings', models.ManyToManyField(to='orders.Toppings')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.carrito')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
