# Generated by Django 3.2.9 on 2021-11-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_pasta_price_pasta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasta',
            name='price_pasta',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=8),
        ),
    ]
