# Generated by Django 3.2.9 on 2021-11-14 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_pasta_price_pasta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regularpizza',
            name='toppings',
        ),
        migrations.RemoveField(
            model_name='sicilianpizza',
            name='toppings',
        ),
        migrations.RemoveField(
            model_name='specialregularpizza',
            name='toppings',
        ),
        migrations.RemoveField(
            model_name='specialsicilianpizza',
            name='toppings',
        ),
    ]
