# Generated by Django 3.2.9 on 2021-11-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20211114_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='price_items',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='regularpizza',
            name='price_reg_pizza',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='sicilianpizza',
            name='price_sic_pizza',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='specialregularpizza',
            name='price_special_reg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='specialsicilianpizza',
            name='price_special_sic',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
    ]
