# Generated by Django 3.2.9 on 2021-11-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20211114_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularpizza',
            name='quantity_top',
            field=models.IntegerField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='sicilianpizza',
            name='quantity_top',
            field=models.IntegerField(blank=True, max_length=1),
        ),
    ]
