# Generated by Django 3.2.9 on 2021-11-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20211114_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subs',
            name='extra_sub',
        ),
        migrations.AlterField(
            model_name='carrito',
            name='items',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
