# Generated by Django 3.2.9 on 2021-11-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20211114_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subs',
            name='price_subs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
    ]
