# Generated by Django 3.2.9 on 2021-11-15 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_subs_price_subs'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
